//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DealsWhat_Admin.Models
{
    public partial class Deal
    {
        public Deal()
        {
            this.Carts = new HashSet<Cart>();
            this.DealComments = new HashSet<DealComment>();
            this.DealImages = new HashSet<DealImage>();
            this.DealOptions = new HashSet<DealOption>();
        }
    
        public Guid Id { get; set; }
        public string ShortTitle { get; set; }
        public string LongTitle { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public double RegularPrice { get; set; }
        public double SpecialPrice { get; set; }
        public string SKU { get; set; }
        public DateTime DateAdded { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string FinePrint { get; set; }
        public string Highlight { get; set; }
        public bool IsFeatured { get; set; }
        public string CanonicalUrl { get; set; }
        public int Status { get; set; }
        public Nullable<Guid> Category_Id { get; set; }
        public Nullable<Guid> Merchant_Id { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual DealCategory DealCategory { get; set; }
        public virtual ICollection<DealComment> DealComments { get; set; }
        public virtual ICollection<DealImage> DealImages { get; set; }
        public virtual ICollection<DealOption> DealOptions { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
