//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DealsWhat_Admin.Models
{
    public partial class Merchant
    {
        public Merchant()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public Guid Id { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string BusinessRegNumber { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public Nullable<double> AddressLat { get; set; }
        public Nullable<double> AddressLng { get; set; }
    
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
